"use client";
import {useMemo,useState,useTransition} from "react";
import {CLIENT_STAGES,CONSULTATION_MODES,HISTORY_FLAGS,OFFER_TYPES,presetOffer,type ConsultationSettings,type Offer,type OfferType} from "../../../consultation/types";
import {saveConsultationSettings} from "../(protected)/reports/[reportId]/actions";

const historyLabels={previous_assessment:"曾做過測驗",previous_consultation:"曾經諮詢",previous_offer_presented:"曾介紹方案",previous_purchase:"曾購買",health_business_previously_discussed:"曾談健康事業",existing_business:"已有副業／事業"} as const;
const blankHistory=Object.fromEntries(HISTORY_FLAGS.map(key=>[key,false])) as ConsultationSettings["consultation_context"]["past_contact"];
function initialValue(saved:ConsultationSettings|null):ConsultationSettings{return saved??{consultation_context:{client_stage:"FIRST_CONTACT",consultation_mode:"FIRST_ANALYSIS",past_contact:blankHistory,allow_health_business_discussion:false},selected_offer:presetOffer("NO_SALE_ANALYSIS_ONLY"),backup_offer:null,coach_notes:""};}

function OfferFields({value,onChange}:{value:Offer;onChange:(value:Offer)=>void}){
  const update=(key:keyof Offer,next:unknown)=>onChange({...value,[key]:next});
  return <div className="consultation-offer-fields"><label>服務名稱<input value={value.offer_name} onChange={e=>update("offer_name",e.target.value)}/></label><label className="full">服務說明<textarea value={value.description} onChange={e=>update("description",e.target.value)}/></label><label>期間<input value={value.duration} onChange={e=>update("duration",e.target.value)}/></label><label>價格顯示<input value={value.price.display} onChange={e=>onChange({...value,price:{...value.price,display:e.target.value}})}/></label><label>價格金額<input type="number" value={value.price.amount??""} onChange={e=>onChange({...value,price:{...value.price,amount:e.target.value===""?null:Number(e.target.value)}})}/></label><label>CTA<input value={value.cta} onChange={e=>update("cta",e.target.value)}/></label><label className="full">其他注意事項<textarea value={value.notes} onChange={e=>update("notes",e.target.value)}/></label></div>;
}

export function ConsultationSettingsForm({reportId,saved}:{reportId:string;saved:ConsultationSettings|null}){
  const [value,setValue]=useState(()=>initialValue(saved));const [status,setStatus]=useState("");const [pending,startTransition]=useTransition();
  const context=value.consultation_context;
  const summary=useMemo(()=>({stage:CLIENT_STAGES[context.client_stage],mode:CONSULTATION_MODES[context.consultation_mode],primary:value.selected_offer.offer_name,backup:value.backup_offer?.offer_name??"無",health:context.allow_health_business_discussion?"是":"否"}),[value,context]);
  const setOfferType=(type:OfferType,backup=false)=>setValue(current=>({...current,[backup?"backup_offer":"selected_offer"]:presetOffer(type)}));
  function save(){setStatus("");startTransition(async()=>{try{await saveConsultationSettings(reportId,value);setStatus("已儲存本次諮詢設定");}catch{setStatus("儲存失敗，請稍後再試");}});}
  return <section className="coach-detail-card full consultation-card"><h2>本次諮詢設定</h2><div className="consultation-grid"><label>客戶目前階段<select value={context.client_stage} onChange={e=>setValue({...value,consultation_context:{...context,client_stage:e.target.value as keyof typeof CLIENT_STAGES}})}>{Object.entries(CLIENT_STAGES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>{context.client_stage==="CUSTOM"&&<input placeholder="輸入其他階段" value={context.client_stage_custom??""} onChange={e=>setValue({...value,consultation_context:{...context,client_stage_custom:e.target.value}})}/>}</label><label>本次諮詢模式<select value={context.consultation_mode} onChange={e=>setValue({...value,consultation_context:{...context,consultation_mode:e.target.value as keyof typeof CONSULTATION_MODES}})}>{Object.entries(CONSULTATION_MODES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>{context.consultation_mode==="CUSTOM"&&<input placeholder="輸入自訂模式" value={context.consultation_mode_custom??""} onChange={e=>setValue({...value,consultation_context:{...context,consultation_mode_custom:e.target.value}})}/>}</label><label>本次主要成交目標<select value={value.selected_offer.offer_type} onChange={e=>setOfferType(e.target.value as OfferType)}>{Object.entries(OFFER_TYPES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>備用方案<select value={value.backup_offer?.offer_type??"NONE"} onChange={e=>e.target.value==="NONE"?setValue({...value,backup_offer:null}):setOfferType(e.target.value as OfferType,true)}><option value="NONE">無</option>{Object.entries(OFFER_TYPES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>
    {value.selected_offer.offer_type==="CUSTOM"&&<OfferFields value={value.selected_offer} onChange={selected_offer=>setValue({...value,selected_offer})}/>} {value.backup_offer?.offer_type==="CUSTOM"&&<OfferFields value={value.backup_offer} onChange={backup_offer=>setValue({...value,backup_offer})}/>}<fieldset className="consultation-history"><legend>過去接觸紀錄</legend>{HISTORY_FLAGS.map(key=><label key={key}><input type="checkbox" checked={context.past_contact[key]} onChange={e=>setValue({...value,consultation_context:{...context,past_contact:{...context.past_contact,[key]:e.target.checked}}})}/>{historyLabels[key]}</label>)}</fieldset><label className="consultation-check"><input type="checkbox" checked={context.allow_health_business_discussion} onChange={e=>setValue({...value,consultation_context:{...context,allow_health_business_discussion:e.target.checked}})}/>允許在適合時詢問健康事業興趣</label><label className="consultation-notes">本次顧問補充指令<textarea placeholder="輸入本次個案背景、談話方向、希望 GPT 特別注意的資訊或成交限制" value={value.coach_notes} onChange={e=>setValue({...value,coach_notes:e.target.value})}/></label><aside className="consultation-summary"><strong>JSON 本次諮詢摘要</strong><span>客戶階段：{summary.stage}</span><span>諮詢模式：{summary.mode}</span><span>主要服務：{summary.primary}</span><span>備用方案：{summary.backup}</span><span>健康事業了解：{summary.health}</span></aside><div className="consultation-save"><button className="button primary" disabled={pending} onClick={save}>{pending?"儲存中…":"儲存本次諮詢設定"}</button>{status&&<span>{status}</span>}</div></section>;
}
